name = "codah-bridge"
main = "bridge.js"
compatibility_date = "2025-10-22"

[vars]
# Optional: override defaults
GEMINI_MODEL = "gemini-1.5-flash-latest"
OPENAI_MODEL = "gpt-4o-mini"

# Secrets to add (in dashboard):
# - GATEWAY_PSK
# - GEMINI_API_KEY
# - OPENAI_API_KEY

