name = "codah-gateway"
main = "gateway.js"
compatibility_date = "2025-10-22"

[vars]
# Comma-separated list of allowed front-end origins (scheme+host+port)
ALLOWED_ORIGINS = "https://your-frontend.example,https://another-allowed.example"

# URL of the bridge worker (origin + route, no trailing slash)
BRIDGE_URL = "https://your-bridge.example.workers.dev"

# Secrets to add (in dashboard):
# - GATEWAY_PSK
