name = "codah-gateway"
main = "gateway.js"
compatibility_date = "2025-10-22"

[vars]
# URL of the Bridge worker (origin + route, no trailing slash)
BRIDGE_URL = "https://YOUR-BRIDGE.example.workers.dev"

# Secrets to add in dashboard:
# - GATEWAY_PSK
